- hosts: all
  become: yes
  become_user: root
  connection: ssh
  gather_facts: no
  pre_tasks:
    - name: update yum
      shell: yum -y update
    - include_vars:
        file: ../../config.json
        name: config
  roles:
    - role: mysql
      vars:
        mysql_port: "{{ config.mysql.port }}"
        mysql_log_dir: "{{ config.mysql.log_dir }}"
        mysql_root_password: "{{ config.mysql.password }}"
        mysql_database: "{{ config.mysql.database }}"
